image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm run deploy
  dependencies:
    - build
