image:
  file: .gitpod.Dockerfile

ports:
  - port: 1313

tasks:
  - name: Start server
    command: hugo server  --buildDrafts --baseUrl $(gp url 1313) --appendPort=false
  - name: Open terminal
    command: git status
    openMode: split-right
