title: Animals and Amplifiers
description: Jekyll Starter Kit
url: https://joey.io
author: joeybeninghove
twitter:
  username: joeybeninghove
  card: summary
logo: /assets/logo.png
social:
  name: Joey Beninghove
  links:
    - https://twitter.com/joeybeninghove

# permalink: /:title/
excerpt_separator: <!--more-->

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:year/:title
  writers:
    output: true
    people: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "writers"
    values:
      layout: "writer"

include:
  - _redirects
exclude:
  - /src
  - /Gemfile
  - /Gemfile.lock
  - /package.json
  - /yarn.lock
  - /yarn-error.log
  - /node_modules
  - /tailwind.config.js
  - /webpack.config.js
  - /postcss.config.js
  - /purgecss.config.js
  - /Procfile.dev
  - /Rakefile
  - /README.md
