title: Ben Crane
description: 
url: https://animalsandamplifiers.surge.sh
author: Ben Crane

collections_dir: collections

collections:
  posts:
    output: true
    permalink: /blog/:year/:title:output_ext
  projects:
    output: true
    permalink: /:collection/:title:output_ext
    order:
      - task_escalator.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

include:
  - _redirects
exclude:
  - /src
  - /Gemfile
  - /Gemfile.lock
  - /package.json
  - /yarn.lock
  - /yarn-error.log
  - /node_modules
  - /tailwind.config.js
  - /webpack.config.js
  - /postcss.config.js
  - /purgecss.config.js
  - /Procfile.dev
  - /Rakefile
  - /README.md
