baseURL: 'https://bencrane.net/'
languageCode: en-us
title: Ben Crane
theme: papermod
paginate: 5

buildDrafts: false
buildFuture: false
buildExpired: false
enableRobotsTXT: true

params:
  ShowReadingTime: true
  
socialIcons:
  - name: "twitter"
    url: "https://twitter.com/bencrane"

menu:
  main: 
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
